# Generated by Django 5.1.6 on 2025-02-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0004_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='trigger_notification_at',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
